// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CircleProgress: typeof import('./src/components/CircleProgress/index.vue')['default']
    Empty: typeof import('./src/components/Empty/index.vue')['default']
    ErrorSimulator: typeof import('./src/components/ErrorSimulator/index.vue')['default']
    IdCardCamera: typeof import('./src/components/IdCardCamera/index.vue')['default']
    IdCardCameraDemo: typeof import('./src/components/IdCardCamera/IdCardCameraDemo.vue')['default']
    OpenApiPicker: typeof import('./src/components/OpenApiPicker/index.vue')['default']
    OpenDatePicker: typeof import('./src/components/OpenDatePicker/index.vue')['default']
    OpenMjDatePicker: typeof import('./src/components/OpenMjDatePicker/index.vue')['default']
    OpenModal: typeof import('./src/components/OpenModal/index.vue')['default']
    OpenTimePicker: typeof import('./src/components/OpenTimePicker/index.vue')['default']
    OpenXfDatePicker: typeof import('./src/components/OpenXfDatePicker/index.vue')['default']
    PasswordTip: typeof import('./src/components/PasswordTip/index.vue')['default']
    ScrollView: typeof import('./src/components/ScrollView/index.vue')['default']
    UploadFile: typeof import('./src/components/UploadFile/index.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSlider: typeof import('vant/es')['Slider']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
